server:
  port: 8081

logging:
  level:
    "liquibase" : debug

spring:
  application:
    name: movie-catalog
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
#    DB username and password is provided via env variables
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  liquibase:
#    DB username and password is provided via env variables
    change-log: classpath:/db/changelog/db.changelog-master.yml
    url: ${spring.datasource.url}
    enabled: true

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5