

spring:
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/moviecatalog
    driver-class-name:
    username: movieapi_user
    password: movieapi_pass
    platform: postgres
  liquibase:
    user: lbmovieapi_user
    password: lbmovieapi_pass
    url: ${spring.datasource.url}

management:
  endpoints:
    web:
      exposure:
        include: "*"

