

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:moviecatalog;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    platform: h2
  #    initialization-mode: embedded
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-test.yml
    user: sa
    password: sa
#    url: ${spring.datasource.url}
  h2:
    console:
      enabled: true
      path: /h2-console


#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
